# Generated by Django 5.2.6 on 2026-01-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='area',
            field=models.CharField(choices=[('A', 'Khu A'), ('B', 'Khu B')], default='A', max_length=1),
        ),
    ]
